#Identação é delimitado pelo bloco
#o interpretador ve a identação e sabe onde começa e termina um bloco
## a cada novo bloco 4 espaços em branco por nivel de identação
def sacar (valor): #inicio do bloco do metodo
    saldo = 500
     
    if saldo >= valor:  #inicio do bloco if
        print("Valor sacado") #so executa se o if for verdade
        print("Retire seu dinheiro na boca do caixa") #so executa se o if for verdade
    
    print("Obrigado por ser nosso cliente") #sempre vai executar porque esta fora do if e esta no metodo

def depositar(valor):
    saldo = 500
    
saldo += Valor

sacar(100)
    
    #fim do bloco if
#fim do bloco def

